release: 0.4
knaufk/flink-junit pull request #6
Opened 2018-12-12 20:12 UTC by austince

Upgraded to support Flink 1.5.

2018-12-23 07:12 UTC, knaufk commented
Thanks @austince and sorry for not getting back earlier. I'l lhave a look at it over the holidays and prepare a new release.

2018-12-23 07:24 UTC, knaufk requested changes

2018-12-23 07:24 UTC, knaufk commented on README.md
> +| 0.4    | 1.5.0  | 1.7 |
If we are planning to support further version of Flink we should remove the note above the compatibility matrix

2018-12-24 15:39 UTC, austince commented on README.md
> +| 0.4    | 1.5.0  | 1.7 |
Why? Won't it still be important for users of this library to know how to match versions to Flink?

2018-12-26 12:21 UTC, knaufk approved these changes

2018-12-26 12:21 UTC, knaufk commented on README.md
> +| 0.4    | 1.5.0  | 1.7 |
We need to keep the table, yes. Currently I have a warning above the table saying that I will not upgrade this library to new Flink version, which we can probably remove now. Anyway, I will just merge and add the commit myself.

2018-12-26 12:21 UTC, merged